spring.application.name=lecture2
spring.devtools.restart.enabled=true

# spring.sql.init.mode=always
spring.datasource.url=jdbc:mysql://localhost:3306/lecture2
spring.datasource.username=root
spring.datasource.password=root1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver