spring.application.name=lecture2
spring.devtools.restart.enabled=true

# spring.sql.init.mode=always
spring.datasource.url=jdbc:mysql://localhost:3306/lecture2
spring.datasource.username=root
spring.datasource.password=root1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# JPA tự tạo/update bảng từ entity class
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.data.redis.host=localhost
spring.data.redis.port=6379
